name: docker-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# top-level permissions help ensure GHCR push works
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive lowercase image name
        id: vars
        shell: bash
        run: |
          owner_lc="${GITHUB_REPOSITORY_OWNER,,}"
          repo="${GITHUB_REPOSITORY#*/}"
          repo_lc="${repo,,}"
          echo "owner_lc=$owner_lc" >> "$GITHUB_OUTPUT"
          echo "repo_lc=$repo_lc"   >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build for PRs (no push)
      - name: Build (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}:pr-${{ github.event.pull_request.number }}

      # Build & push on main
      - name: Build & push (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}:latest
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}:${{ github.sha }}
