name: docker-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build only for PRs (no push)
      - name: Build (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/linux-git-labs:pr-${{ github.event.pull_request.number }}

      # Build & push on main
      - name: Build & push (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/linux-git-labs:latest
            ghcr.io/${{ github.repository_owner }}/linux-git-labs:${{ github.sha }}
