name: shellcheck
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        shell: bash
        run: |
          set -euo pipefail
          # Find all *.sh files robustly (no globstar needed)
          mapfile -d '' files < <(find . -type f -name '*.sh' -print0)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No shell scripts to lint."
            exit 0
          fi
          shellcheck "${files[@]}"
